# Try to find the EGL library
#  EGL_FOUND - system has EGL
#  EGL_INCLUDE_DIR - the EGL include directory
#  EGL_LIBRARY - the EGL library

# Add EGL_ROOT to search paths if defined
IF(DEFINED ENV{EGL_ROOT})
    SET(EGL_ROOT $ENV{EGL_ROOT})
ENDIF()

IF(DEFINED EGL_ROOT)
    SET(EGL_INCLUDE_DIR "${EGL_ROOT}/include")
    SET(EGL_LIBRARY "${EGL_ROOT}/lib/libEGL.dll.lib")
ELSE()
    # Add vcpkg search paths
    IF(DEFINED VCPKG_TARGET_TRIPLET)
        SET(VCPKG_INSTALLED_DIR "${CMAKE_CURRENT_SOURCE_DIR}/vcpkg_installed/${VCPKG_TARGET_TRIPLET}")
        SET(EGL_INCLUDE_DIR "${VCPKG_INSTALLED_DIR}/include")
        SET(EGL_LIBRARY "${VCPKG_INSTALLED_DIR}/lib/libEGL.lib")
    ELSE()
        FIND_PATH(EGL_INCLUDE_DIR NAMES EGL/egl.h)
        SET(_EGL_STATIC_LIBS libEGL.a)
        SET(_EGL_SHARED_LIBS libEGL.lib libEGL.dll.a EGL)
        FIND_LIBRARY(EGL_LIBRARY NAMES ${_EGL_SHARED_LIBS} ${_EGL_STATIC_LIBS})
    ENDIF()
ENDIF()

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(EGL DEFAULT_MSG EGL_LIBRARY EGL_INCLUDE_DIR)
MARK_AS_ADVANCED(EGL_LIBRARY EGL_INCLUDE_DIR)
