# Try to find the OpenGLES2 library
#  OPENGLES2_FOUND - system has OpenGL ES 2.0
#  OPENGLES2_INCLUDE_DIR - the OpenGL ES 2.0 include directory
#  OPENGLES2_LIBRARY - the OpenGL ES 2.0 library

# Add ANGLE_ROOT to search paths if defined
IF(DEFINED ENV{ANGLE_ROOT})
    SET(ANGLE_ROOT $ENV{ANGLE_ROOT})
ENDIF()

IF(DEFINED ANGLE_ROOT)
    SET(OPENGLES2_INCLUDE_DIR "${ANGLE_ROOT}/include")
    SET(OPENGLES2_LIBRARY "${ANGLE_ROOT}/lib/libGLESv2.dll.lib")
ELSE()
    # Add vcpkg search paths
    IF(DEFINED VCPKG_TARGET_TRIPLET)
        SET(VCPKG_INSTALLED_DIR "${CMAKE_CURRENT_SOURCE_DIR}/vcpkg_installed/${VCPKG_TARGET_TRIPLET}")
        SET(OPENGLES2_INCLUDE_DIR "${VCPKG_INSTALLED_DIR}/include")
        SET(OPENGLES2_LIBRARY "${VCPKG_INSTALLED_DIR}/lib/libGLESv2.lib")
    ELSE()
        FIND_PATH(OPENGLES2_INCLUDE_DIR NAMES GLES2/gl2.h)
        SET(_OPENGLES2_STATIC_LIBS libGLESv2.a)
        SET(_OPENGLES2_SHARED_LIBS libGLESv2.lib libGLESv2.dll.a GLESv2)
        FIND_LIBRARY(OPENGLES2_LIBRARY NAMES ${_OPENGLES2_SHARED_LIBS} ${_OPENGLES2_STATIC_LIBS})
    ENDIF()
ENDIF()

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(OpenGLES2 DEFAULT_MSG OPENGLES2_LIBRARY OPENGLES2_INCLUDE_DIR)
MARK_AS_ADVANCED(OPENGLES2_LIBRARY OPENGLES2_INCLUDE_DIR)
